### ISSUE TITLE
Contributing to the new C client library

### ISSUE THREAD

**Issue by woehrl01** [JumpMind/symmetric-ds#4]
I'm highly interested in contributing to the newly published c library, because it would reduce the requirement to install the java JRE on "simple" client nodes.

As there is still a lot of code missing in each of the services, there are a few questions, before I would start.

* Is it wanted to contribute to this one or should we wait till it's fully working?

If it's wanted:

* Should it be a (kind of) direct port of the java classes? 
* Should there be also the *SqlMap classes or should those be inlined?
* I would need it to work on Windows plattforms. Is it wanted to add ```#ifdef``` if those are required to make cross plattform incompatibilities to work?
* Which services are "free to contribute", so contributers are not doing duplicate work?

**Comment by erilong** [comment]
The C library is designed for a specific project that needs to run a simplified, single-threaded SymmetricDS client on an embedded Linux ARM device that uses the SQLite database.  The project needs to be delivered within a month, so there will be a lot of activity in a short period.  In the next couple weeks, the code base should start to solidify into a style where you can see how to implement new things, and it would be possible to take on contributions at that point.  It will be a bare bones implementation, with single threading, default routing, only SQLite support, no conflicts, no transformations, no job scheduling, no file sync, and no server functionality.

We'd like to follow the Java classes and write corresponding OO code in C where it's a reasonable fit.  We're only implementing what we need at first, so it should be easy to add missing features by finding them in Java and implementing them in the same place in C.  Java has many liberties, so we'd prefer readability and performance of C code above line-by-line porting.  For example, we chose the Curl library API for HTTP/S transport, which delivers data in callbacks instead of a polling method, so the reader/writer looks a little different in C.

It would be great if you want to help out with getting things to compile on Windows, implementing a dialect for another database platform, and adding features beyond the initial set.  Using #ifdef to handle cross platform compilations makes sense to me.  What database are you using?

**Comment by woehrl01** [comment]
Sounds pretty good to me! 

Currently I also only need SQLite (with encryption), and a "stripped" version is totally enough for my use cases, too. I also thought about waiting till there are a few scenarios implemented, to apply the same style to additional features. 

It would be great if you comment this issues if you think that you have a feature set where contributions are free to happen. 

Looking forward to adding features to an amazing product!
